# Generated by Django 3.2.4 on 2021-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='forsearch',
            field=models.BooleanField(default=True),
        ),
    ]
